## METHOD CHAINING

In [1]:
import pandas as pd

In [47]:
path_1 = "./data/mexico-real-estate-1.csv"
path_2 = "./data/mexico-real-estate-2.csv"
path_3 = "./data/mexico-real-estate-3.csv"

In [50]:

df1 = pd.read_csv(path_1)
df2 = pd.read_csv(path_2)
df3 = pd.read_csv(path_3)

In [51]:

df1.head()

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"

In [52]:

df2.head()

  property_type       state        lat         lon  area_m2  price_mxn
0     apartment  Nuevo León  25.721081 -100.345581     72.0  1300000.0
1     apartment      Puebla        NaN         NaN    190.0  2500000.0
2         house     Morelos  23.634501 -102.552788    360.0  5300000.0
3         house     Morelos        NaN         NaN     76.0   820000.0
4         house      Puebla        NaN         NaN    200.0  1100000.0

In [53]:

df3.head()

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,NaN,275.0,263432.41
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67

In [57]:
df2 = (
    pd.read_csv(path_2)

    # Create "price_usd" column (19 pesos to the dollar in 2014)
    .assign(price_usd = lambda x: x["price_mxn"].div(19))

    # Drop "price_mxn" column
    .drop(columns=["price_mxn"])

    # Drop null values
    .dropna()
)

In [66]:
# Print object type, shape, and head
print(f"df2 type: {type(df2)}")
print(f"df2 shape: {df2.shape}\n")
df2.head()

df2 type: <class 'pandas.DataFrame'>
df2 shape: (571, 6)

,property_type,state,lat,lon,area_m2,price_usd
0,apartment,Nuevo León,25.721081,-100.345581,72.0,68421.052632
2,house,Morelos,23.634501,-102.552788,360.0,278947.368421
6,apartment,Estado de México,19.272040,-99.572013,85.0,65789.473684
7,house,San Luis Potosí,22.138882,-100.996510,158.0,111578.947368
8,apartment,Distrito Federal,19.394558,-99.129707,65.0,39904.736842

In [70]:
print(f"df1 columns: {df1.columns.tolist()}")
print(f"df2 columns: {df2.columns.tolist()}")
print(f"df3 columns: {df3.columns.tolist()}")

df1 columns: ['property_type', 'state', 'lat', 'lon', 'area_m2', 'price_usd']
df2 columns: ['property_type', 'state', 'lat', 'lon', 'area_m2', 'price_usd']
df3 columns: ['property_type', 'place_with_parent_names', 'lat-lon', 'area_m2', 'price_usd']

In [73]:
(
    pd.read_csv(path_3)
    ["lat-lon"]
    .str.split(",", expand=True)[0]
    .astype(float)
    .head()
)

0    19.525890
1    19.264054
2    19.268629
3          NaN
4    19.511938
Name: 0, dtype: float64

In [74]:
(
    pd.read_csv(path_3)
    ["lat-lon"]
    .str.split(",", expand=True)[1]
    .astype(float)
    .head()
)

0   -99.151703
1   -99.572753
2   -99.671722
3          NaN
4   -96.871956
Name: 1, dtype: float64

In [75]:
(
    pd.read_csv(path_3)
    ["place_with_parent_names"]
    .str.split("|", expand=True)
    .head()
)

,0,1,2,3,4,5,6
0,,México,Distrito Federal,Gustavo A. Madero,Acueducto de Guadalupe,,NaN
1,,México,Estado de México,Toluca,Metepec,,NaN
2,,México,Estado de México,Toluca,Toluca de Lerdo,Ocho Cedros,
3,,México,Morelos,Temixco,Burgos Bugambilias,,NaN
4,,México,Veracruz de Ignacio de la Llave,Veracruz,,NaN,NaN

In [77]:
(
    pd.read_csv(path_3)
    ["place_with_parent_names"]
    .str.split("|", expand=True)[2]
    .head()
)

0                   Distrito Federal
1                   Estado de México
2                   Estado de México
3                            Morelos
4    Veracruz de Ignacio de la Llave
Name: 2, dtype: str

In [78]:
df3 = (
    pd.read_csv(path_3)
    # Drop null values from df3
    .dropna()
    # Create "lat" and "lon" columns for df3
    .assign(lat=lambda x: x["lat-lon"]
                .str.split(",", expand=True)[0]           
                .astype(float),
            lon=lambda x: x["lat-lon"]
                .str.split(",", expand=True)[1]           
                .astype(float),
            # Create "state" column for df3
            state=lambda x: x["place_with_parent_names"]
            .str.split("|", expand=True)[2]
           )
    
    # Drop "place_with_parent_names" and "lat-lon" from df3
    .drop(columns=["place_with_parent_names", "lat-lon"])
            
    
)

In [80]:
# Print object type, shape, and head
print("df3 type:", type(df3))
print("df3 shape:", df3.shape)
df3.head()

df3 type: <class 'pandas.DataFrame'>
df3 shape: (582, 6)

,property_type,area_m2,price_usd,lat,lon,state
0,apartment,71.0,48550.59,19.525890,-99.151703,Distrito Federal
1,house,233.0,168636.73,19.264054,-99.572753,Estado de México
2,house,300.0,86932.69,19.268629,-99.671722,Estado de México
4,apartment,84.0,68508.67,19.511938,-96.871956,Veracruz de Ignacio de la Llave
5,house,175.0,102763.00,20.689157,-103.366728,Jalisco

In [32]:
# data = (
#     pd.read_csv(path_1)
#     .dropna()
#     .info()

# )

<class 'pandas.DataFrame'>
Index: 583 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  583 non-null    str
 1   state          583 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        583 non-null    float64
 5   price_usd      583 non-null    str
dtypes: float64(3), str(3)
memory usage: 48.6 KB

In [36]:

def clean_dataset(path_1):
    return (
        pd.read_csv(path_1)
         .dropna()
    )

In [39]:

data = clean_dataset(path_1)
data.head()

  property_type             state        lat         lon  area_m2    price_usd
0         house  Estado de México  19.560181  -99.233528    150.0   $67,965.56
1         house        Nuevo León  25.688436 -100.198807    186.0   $63,223.78
2     apartment          Guerrero  16.767704  -99.764383     82.0   $84,298.37
3     apartment          Guerrero  16.829782  -99.911012    150.0   $94,308.80
5         house           Yucatán  21.052583  -89.538639    205.0  $105,191.37

In [41]:

# how large is this DataFrame exactly?
data.shape

(583, 6)

In [42]:

# deserves its own spotlight
data.info()

<class 'pandas.DataFrame'>
Index: 583 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  583 non-null    str
 1   state          583 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        583 non-null    float64
 5   price_usd      583 non-null    str
dtypes: float64(3), str(3)
memory usage: 48.6 KB

In [44]:

# cleaner view of the type column.
data.dtypes

property_type        str
state                str
lat              float64
lon              float64
area_m2          float64
price_usd            str
dtype: object

In [45]:

# where exactly are the missing values?
data.isnull().sum()

property_type    0
state            0
lat              0
lon              0
area_m2          0
price_usd        0
dtype: int64

In [81]:

# Check if all column sets are identical
columns_match = set(df1.columns) == set(df2.columns) == set(df3.columns)

if columns_match:
    print("✅ All DataFrames have the same columns.")
else:
    print("❌ Column mismatch detected!")
    # Optional: See the difference
    print("df1 vs df2 diff:", set(df1.columns) ^ set(df2.columns))
    print("df2 vs df3 diff:", set(df2.columns) ^ set(df3.columns))

✅ All DataFrames have the same columns.

In [82]:

# Stack df1, df2, and df3 vertically
# df = pd.concat(..., ignore_index=True)
df = pd.concat([df1, df2, df3], ignore_index=True)

# Verify the result
print(f"Combined Shape: {df.shape}")
df.head()

Combined Shape: (1853, 6)

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"

In [85]:

df.isnull().sum()

property_type      0
state              0
lat              117
lon              117
area_m2            0
price_usd          0
dtype: int64